-- INSERT INTO clientes ( nombre, apellido, dni, anio) VALUES ('Matias','Abarca','12345',27), ('John','Doe','12345',30);
-- INSERT INTO productos (nombre, stock, precio, creado_en) VALUES ('Bicicleta',20,5000, NOW()),('Play 5',10,10000, NOW());
-- INSERT INTO items_comprobante (cantidad, producto_id ) VALUES (3, 1), (2, 2);
-- INSERT INTO comprobantes ( creado_en, descripcion, cliente_id, item_id) VALUES  (NOW(),'',1,1), (NOW(),'',2,2);
